### ISSUE TITLE
为什么布局不能宽度百分百？

### ISSUE THREAD

**Issue by wZuriel** [goweii/AnyLayer#10]
<img width="373" alt="20190226-115723 2x" src="https://user-images.githubusercontent.com/15941713/53386672-1a572900-39be-11e9-9f75-996bc59eefe6.png">
<img width="762" alt="20190226-115654 2x" src="https://user-images.githubusercontent.com/15941713/53386673-1a572900-39be-11e9-9f07-6ff040fce1de.png">

**Comment by goweii** [comment]
贴一下调用的代码。
应该是因为你的contentView是在外部inflate出来的，这样解析布局文件时并不会解析layout_开头的属性。你可以试试直接调用contentView(int layoutId)方法传入布局ID。

**Comment by wZuriel** [comment]
我是直接调用contentView(int layoutId)方法传入布局ID的这个方法，但是还是不行。最后只能强行把contentView的宽度设置成屏幕宽度。
<img width="787" alt="qq20190226-184244 2x" src="https://user-images.githubusercontent.com/15941713/53407156-70e05980-39f6-11e9-8d12-8bde19adc53d.png">

**Comment by goweii** [comment]
看你的代码应该没有问题和DEMO中是一样的。
这个语言我不是很熟悉，你最后的initSortView(layerSort)方法是初始化什么的？
不行你先更新下最新版，打断点调试下吧，我也不清楚了。

**Comment by wZuriel** [comment]
> 看你的代码应该没有问题和DEMO中是一样的。
> 这个语言我不是很熟悉，你最后的initSortView(layerSort)方法是初始化什么的？
> 不行你先更新下最新版，打断点调试下吧，我也不清楚了。
就是初始化布局文件里面的recycleview，没有做其他操作

**Comment by hardlove** [comment]
遇到同样的问题，不知怎么解决

**Comment by goweii** [comment]
你贴一下布局文件和完整的调用和初始化代码，我粘到DEMO中调试一下。
因为DEMO中是可以的，看了好几天都没发现是哪的问题。

**Comment by goweii** [comment]
已在3.2.0版已修复
代码重构，类名属性变化较大，更新需考虑。
