### ISSUE TITLE
可以让跟随targetView滑动吗？

### ISSUE THREAD

**Issue by ChillingVan** [goweii/AnyLayer#12]
1. 可以使用targetView.getViewTreeObserver().addOnScrollChangedListener来监听target的滑动事件
2. PopupWindow有类似的功能
3. 目前看了下应该是不可以的，demo好像弹出popup后也动不了了。
如有误请斧正

然后看了下似乎是用margin来控制弹出的坐标的，个人感觉用layout方法好些

**Comment by goweii** [comment]
感谢建议，这个功能我也在考虑，有空再实现。

**Comment by goweii** [comment]
已实现跟随targetView滑动，需设置outsideInterceptTouchEvent(false)可响应底部Activity的事件

**Comment by goweii** [comment]
需升级到2.5.0版

**Comment by ChillingVan** [comment]
谢谢，试了一下，demo里关不了这个Popup了，不过小问题。
