### ISSUE TITLE
棒棒棒！

### ISSUE THREAD

**Issue by funnyzhaov** [goweii/AnyLayer#15]
希望库主可以更新了设计思路，给了小star的同学们想学习学习哈~ (^_−)☆

**Comment by goweii** [comment]
文档一直想写，但是一直没有时间整理（其实是因为懒），周末我有空先整理下基本的介绍和用法，原理后面补上。

**Comment by goweii** [comment]
抱歉，这周末没时间写。下周周内加班补上。 @

**Comment by funnyzhaov** [comment]
期待中

**Comment by goweii** [comment]
写了一部分了，写文档比写代码还累，唉~

**Comment by funnyzhaov** [comment]
看到你的文档啦，很详细~~  我得仔细看看
