### ISSUE TITLE
Anylayer会自动获取焦点的问题

### ISSUE THREAD

**Issue by CaopanHuster** [goweii/AnyLayer#21]
使用中如果edittext拥有焦点，键盘处于展开状态，这时候用anylayer弹出popu会导致edittext失去焦点，键盘状态不变，但是无法输入，请问有好的解决办法

**Comment by goweii** [comment]
可以显示后手动给edittext设置焦点

**Comment by goweii** [comment]
后者去掉layer抢占焦点（interceptKeyEvent=false）,但是这样就不支持物理返回键关闭了

**Comment by CaopanHuster** [comment]
> 后者去掉layer抢占焦点（interceptKeyEvent=false）,但是这样就不支持物理返回键关闭了

明白了 非常感谢，想不到回答的这么具体
