### ISSUE TITLE
Toast在全屏背景变暗的情况下浮层优先级低

### ISSUE THREAD

**Issue by SSSSunrise** [goweii/AnyLayer#24]
![image](https://user-images.githubusercontent.com/31717774/86503711-1b367100-bde3-11ea-8a97-8cdf5766e71d.png)
当我show了一个 DialogFragment 全屏背景变暗 再showToast会发生这种情况
（稍微自定义了一下Toast的样式 ^_^）

**Comment by goweii** [comment]
用anylayer实现的toast本质上是当前activity上add的一个view，所以肯定在原生dialog的下面。

**Comment by SSSSunrise** [comment]
行吧
