### ISSUE TITLE
怎么再dialogfragment层级上显示DialogLayer

### ISSUE THREAD

**Issue by panlinn** [goweii/AnyLayer#26]
在dialogfragment上调用AnyLayer.dialog(context).{...}.show()会出现layer显示在dialogfragment下面，请问下这种情况怎么处理

**Comment by goweii** [comment]
使用下面这种方式创建layer，会启动一个透明Activity显示layer
``` java
public static void dialog(LayerActivity.OnLayerCreatedCallback callback) {
    LayerActivity.start(ActivityHolder.getApplication(), callback);
}
```

**Comment by panlinn** [comment]
普通情况下能解决，但如果依赖的activity注册了android:process，ActivityHolder.getApplication()获取的context会导致启动界面失败

**Comment by goweii** [comment]
可以自己实现个透明activity做载体，不过这样就不具有通用性了。这种情况还是建议采用系统dialog实现。
