### ISSUE TITLE
长按Edittext会弹出：全选、复制（系统自带的弹窗），怎么处理点击空白自动消失

### ISSUE THREAD

**Issue by 1170762202** [goweii/AnyLayer#30]
长按Edittext会弹出：全选、复制（系统自带的弹窗），怎么处理点击空白自动消失，目前是点击该控件，弹窗才会消失

**Comment by goweii** [comment]
这个是系统弹窗，可以通过取消输入框焦点关闭。你可以给background和content绑定事件自己处理。

**Comment by 1170762202** [comment]
好的，想问下怎么自定义这个系统弹窗，有思路吗

**Comment by 1170762202** [comment]
像微信那种

**Comment by goweii** [comment]
用Popup自定义
