### ISSUE TITLE
compatSoftInput概率性出现将DialogLayer移动过于高的问题

### ISSUE THREAD

**Issue by HarveyLee1228** [goweii/AnyLayer#34]
我的用法  
mDialog?.onVisibleChangeListener(object :
            Layer.OnVisibleChangeListener {
            override fun onShow(layer: Layer) {
                (layer as DialogLayer).compatSoftInput(true, etNote)
            }

            override fun onDismiss(layer: Layer) {
                (layer as DialogLayer).removeSoftInput()
            }
        })
场景是一个底部弹出且始终处于底部的浮层，浮层内部一个输入框一个按钮。

**Comment by goweii** [comment]
4.1.3已修复
