### ISSUE TITLE
请问以popup展示时，是否支持背景全变暗效果

### ISSUE THREAD

**Issue by hardlove** [goweii/AnyLayer#35]
是否支持如下效果:
![image](https://user-images.githubusercontent.com/11812893/103966879-b6960d80-519b-11eb-8db7-57f24b443fb7.png)
当前做出来的效果是这样的，满足不了需求：
![image](https://user-images.githubusercontent.com/11812893/103966942-d75e6300-519b-11eb-9612-fa93fdbcd102.png)

**Comment by goweii** [comment]
取消背景对齐 backgroundAlign(false)

**Comment by hardlove** [comment]
> 取消背景对齐 backgroundAlign(false)

非常感谢，问题解决
