### ISSUE TITLE
您好，请问如何设置pop以外的部分view点击不消失

### ISSUE THREAD

**Issue by HuYueling** [goweii/AnyLayer#40]
如题，我的pop展示在menulayout下面，但是有做留白空隙，如何点击空隙处pop不消失

**Comment by goweii** [comment]
没理解，上图？

**Comment by HuYueling** [comment]
![image](https://user-images.githubusercontent.com/30490259/115833846-182a7100-a447-11eb-831e-3b0a881a2afa.png)
让点击圈中的地方点击不消失

**Comment by goweii** [comment]
这个默认的属性是实现不了了，你可以继承自己实现。

**Comment by HuYueling** [comment]
好的，谢谢
