### ISSUE TITLE
AnyLayer.dialog 滚动视图不显示滚动条

### ISSUE THREAD

**Issue by protectedMan** [goweii/AnyLayer#43]
版本4.1.4-androidx
代码位于demo的 per/goweii/android/anylayer/DragActivity.java:66
嵌入ScrollView 或者Recyleview等滚动视图是不显示滚动条,
我自己的项目是这种情况, 使用demo 也是这种情况. 
按理说应该显示滚动条的,不知道是为什么
![QQ20210513-160633](https://user-images.githubusercontent.com/17565737/118097456-4c210280-b405-11eb-92b0-23cb3115d3c2.gif)

**Comment by goweii** [comment]
这你查查资料，不属于库问题。
