### ISSUE TITLE
依赖加载不到

### ISSUE THREAD

**Issue by h923745834** [goweii/AnyLayer#44]
我使用Android Studio 4.2 beta 5版本，没使用代理。编译时报如下错误：
Could not resolve com.github.goweii:AnyLayer:4.1.4-androidx.
         > Could not get resource 'https://dl.bintray.com/tencentqcloudterminal/maven/com/github/goweii/AnyLayer/4.1.4-androidx/AnyLayer-4.1.4-androidx.pom'.
            > Could not HEAD 'https://dl.bintray.com/tencentqcloudterminal/maven/com/github/goweii/AnyLayer/4.1.4-androidx/AnyLayer-4.1.4-androidx.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.github.goweii:AnyLayer:4.1.4-androidx.
         > Could not get resource 'https://dl.bintray.com/umsdk/release/com/github/goweii/AnyLayer/4.1.4-androidx/AnyLayer-4.1.4-androidx.pom'.
            > Could not HEAD 'https://dl.bintray.com/umsdk/release/com/github/goweii/AnyLayer/4.1.4-androidx/AnyLayer-4.1.4-androidx.pom'. Received status code 403 from server: Forbidden

**Comment by goweii** [comment]
加jitpack仓库了？

**Comment by h923745834** [comment]
> 加jitpack仓库了？

有的，我按你的文档配置的依赖。后面我Android studio 安装回4.0版本，可以正常加载到anylayer库。
