### ISSUE TITLE
4.1.5-androidx

### ISSUE THREAD

**Issue by GaoFuq** [goweii/AnyLayer#46]
build报错如下：
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve per.goweii.visualeffect:visualeffect-core:1.0.3.
     Required by:
         project :app > com.github.goweii.AnyLayer:anylayer:4.1.5-androidx
      > Could not resolve per.goweii.visualeffect:visualeffect-core:1.0.3.
         > Could not get resource 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-core/1.0.3/visualeffect-core-1.0.3.pom'.
            > Could not HEAD 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-core/1.0.3/visualeffect-core-1.0.3.pom'. Received status code 403 from server: Forbidden
   > Could not resolve per.goweii.visualeffect:visualeffect-blur:1.0.3.
     Required by:
         project :app > com.github.goweii.AnyLayer:anylayer:4.1.5-androidx
      > Could not resolve per.goweii.visualeffect:visualeffect-blur:1.0.3.
         > Could not get resource 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-blur/1.0.3/visualeffect-blur-1.0.3.pom'.
            > Could not HEAD 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-blur/1.0.3/visualeffect-blur-1.0.3.pom'. Received status code 403 from server: Forbidden
   > Could not resolve per.goweii.visualeffect:visualeffect-view:1.0.3.
     Required by:
         project :app > com.github.goweii.AnyLayer:anylayer:4.1.5-androidx
      > Could not resolve per.goweii.visualeffect:visualeffect-view:1.0.3.
         > Could not get resource 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-view/1.0.3/visualeffect-view-1.0.3.pom'.
            > Could not HEAD 'https://dl.bintray.com/rongcloud/maven/per/goweii/visualeffect/visualeffect-view/1.0.3/visualeffect-view-1.0.3.pom'. Received status code 403 from server: Forbidden
---------------------------------------------------------------------------------------------------------------
    我加上maven { url "https://gitee.com/goweii/maven-repository/raw/master/releases/" }，build成功了。但是app运行报错，如下：
 java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/...
------------------------------------------------------------------------------------------------------------------------
这是要我依赖startup吗？求解决

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/119926427-fe320000-bfa9-11eb-9a6a-561f9466cd38.png)

**Comment by GaoFuq** [comment]
我加了startup依赖，build成功，但运行报错，如上图。

**Comment by goweii** [comment]
在binddata回调绑定数据

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/119937231-05163e00-bfbd-11eb-8093-ce6c391014a5.png)

**Comment by GaoFuq** [comment]
走 getViewHolder().getDecor().removeCallbacks(mShowRunnable);方法没有dismiss掉dialog

**Comment by GaoFuq** [comment]
没有报错，就是dismiss不起作用。

**Comment by goweii** [comment]
你什么时候调用的dismiss，贴下使用的代码。

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/120073901-ed2ddf80-c0cc-11eb-9a84-33142cb5cea3.png)

**Comment by GaoFuq** [comment]
就是普通的网络请求，得到数据结果后，调用的dismiss

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/120073992-39791f80-c0cd-11eb-9508-def08bb067a8.png)

**Comment by GaoFuq** [comment]
可以就修改4.1.4-androidx的ViewManager的bug吗？

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/120074088-d471f980-c0cd-11eb-9505-281c4adb9ddb.png)

**Comment by GaoFuq** [comment]
![image](https://user-images.githubusercontent.com/45843335/120074120-f79ca900-c0cd-11eb-8d76-e40d189c000d.png)

**Comment by goweii** [comment]
升级4.1.6

**Comment by protectedMan** [comment]
同403加载异常
