### ISSUE TITLE
背景的明暗渐变和窗体的动画延迟太大，应该要一起进行

### ISSUE THREAD

**Issue by junixapp** [goweii/AnyLayer#5]

**Comment by goweii** [comment]
是一起执行的，如果效果不理想，可以调用backgroundAnim自行设置

**Comment by li-xiaojun** [comment]
对话框移除后，背景的半透明灰色仍然停留300毫秒左右才消失，demo里面都是这样的

**Comment by goweii** [comment]
背景默认显示动画为300毫秒，和窗口的动画是同时执行的，但不一定同时完成。demo截图里的效果是没有问题的，你提的问题我还是没理解具体是什么，可以录制一个gif吗？

**Comment by li-xiaojun** [comment]
我期望的是背景的动画和窗口的动画能同时执行，这个类库支持吗

**Comment by goweii** [comment]
库中背景和窗体的动画是同时调用的。你可以看一下源码。

**Comment by li-xiaojun** [comment]
那为什么demo中的效果不是同时执行的呢？

**Comment by goweii** [comment]
我这边demo是同时执行的。不知道你那边不同时的效果是什么样子的，还是录制一个gif吧！

**Comment by goweii** [comment]
抱歉，我一直是直接跑的项目，没下载demo的apk安装。今天发现demo下载链接粘贴错了，现在已经修正了，你再试下。
