### ISSUE TITLE
屏幕底部 DialogLayer包含EditText 的 view 动态隐藏，键盘弹起，导致窗口与键盘之间有空白

### ISSUE THREAD

**Issue by kakarrot** [goweii/AnyLayer#52]
compatSoftInput(true) 设置以后，第一次 弹窗 下层的view 也跟随上移，点击让弹窗dimiss()，再show()，则正常显示

**Comment by goweii** [comment]
5.0.0-alpha03修复了这个问题，但是重命名了很多类和方法，**不兼容4.x.x版本**。

1. 为啥没在4.x.x版本做兼容更新？
因为没精力维护这么多分支了。而且5.0.0也将会是最后一个稳定版。
2. 为啥是alpha版本？
因为正在考虑剥离高斯模糊成单独依赖。重构完成后将发布5.0.0正式版。
3. 为啥5.0.0之后不维护了？
因为我已经重构了一个新库**Layer**，暂时没开源，还在自用调试。
