### ISSUE TITLE
4.1.6-androidx  visualeffect 403

### ISSUE THREAD

**Issue by protectedMan** [goweii/AnyLayer#53]
Could not GET 'https://dl.bintray.com/shamschu/maven/per/goweii/visualeffect/visualeffect-core/1.0.3/visualeffect-core-1.0.3.pom'. Received status code 403 from server: Forbidden
不知道什么原因

jitpack的maven仓库已经配置好了

**Comment by goweii** [comment]
使用4.1.5及以后版本必须添加，因高斯模糊用到的VisualEffect库暂时只发布在gitee仓库

maven { url "https://gitee.com/goweii/maven-repository/raw/master/releases/" }
