### ISSUE TITLE
全面屏适配存在问题

### ISSUE THREAD

**Issue by 976112643** [goweii/AnyLayer#6]
底部不全屏

**Comment by goweii** [comment]
手机型号是什么？我在小米8和vivo哪个刘海屏测试是没有问题的。
框架是在当前Activity上动态添加一个view以实现悬浮窗效果，占用空间和当前Activity大小相同。

**Comment by 976112643** [comment]
- 小米mix2

- 系统 8.0 

- miui10

- 开启了全面屏手势

出现的效果如下: 
 ![TIM图片20181217233045.png](http://img.akawok.com/repertory-image201812172331152552.jpg)
![TIM图片20181217233051.png](http://img.akawok.com/repertory-image201812172331589084.jpg)

**Comment by goweii** [comment]
源码效果是好的，我把demo传错了，现在好了，你重新下载demo试下。
