### ISSUE TITLE
使用view报错

### ISSUE THREAD

**Issue by zaaach** [goweii/AnyLayer#9]
```
View view = LayoutInflater.from(context).inflate(R.layout.dialog_confirm, null);
AnyLayer.with(context)
                .cancelableOnClickKeyBack(true)
                .cancelableOnTouchOutside(true)
                .contentView(view)
.show()
```
报错Attempt to write to field 'int android.widget.FrameLayout$LayoutParams.gravity' on a null object reference

**Comment by goweii** [comment]
已修复。
但仍建议ContentView采用布局ID的方式传入，不建议采用该方法。因为在外部inflate的时候无法获取到ContentView的父布局，即无法依据XML中的layout_开头的属性构建LayoutParams。会导致显示问题。

**Comment by zaaach** [comment]
好的，谢谢
